# Generated by Django 4.1.2 on 2023-04-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
