# Generated by Django 4.1.2 on 2023-04-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_entry_authors_remove_entry_blog_delete_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdatetime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('userid', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('useremail', models.EmailField(max_length=254)),
                ('usercontact', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('orderamount', models.CharField(max_length=200)),
                ('paymentvia', models.CharField(max_length=200)),
                ('paymentmethod', models.CharField(max_length=200)),
                ('transactionid', models.TextField()),
            ],
        ),
    ]
